language: objective-c
osx_image: xcode9.2

env:
  matrix:
    - CEDAR_SDK_VERSION="11.2" CEDAR_SDK_RUNTIME_VERSION="8.1" TASK="rake ci"
    - CEDAR_SDK_VERSION="11.2" CEDAR_SDK_RUNTIME_VERSION="11.2" TASK="rake ci"

    # Analyze takes too long -- vary on runtime SDK
    - CEDAR_SDK_VERSION="11.2" CEDAR_SDK_RUNTIME_VERSION="11.2" TASK="rake suites:specs:analyze"
    - CEDAR_SDK_VERSION="11.2" CEDAR_SDK_RUNTIME_VERSION="11.2" TASK="rake suites:uispecs:analyze"
    - CEDAR_SDK_VERSION="11.2" CEDAR_SDK_RUNTIME_VERSION="11.2" TASK="rake suites:focused_specs:analyze"

    - TASK="./install.sh"
    - TASK="./installCodeSnippetsAndTemplates"

before_install: brew update
install:
  - bundle install
  - brew install ios-sim

script:
    # run a printer task to keep travis from terminating static analysis
    - 'while true; do echo "(waiting)"; sleep 60; done &'
    - $TASK
    - kill %1
